name: Deploy Laravel App to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, intl, xml, curl, zip, opcache

      - name: Install dependencies
        run: |
          composer global require "composer/composer:2.*"  # Installe Composer 2
          composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            PROJECT_PATH="${{ secrets.PROJECT_PATH }}"

            if [ ! -d "$PROJECT_PATH" ]; then
              mkdir -p "$PROJECT_PATH"
            fi

            cd "$PROJECT_PATH"

            if [ ! -d ".git" ]; then
              git clone https://github.com/Granules-de-Bois-Picard/api.git .
            else
              git pull origin production
            fi

            if [ ! -f .env ]; then
              cp .env.example .env
            fi

            sed -i "s/^APP_NAME=.*/APP_NAME=${{ secrets.APP_NAME }}/" .env

            sed -i "s/^DB_CONNECTION=.*/DB_CONNECTION=${{ secrets.DB_CONNECTION }}/" .env
            sed -i "s/^DB_HOST=.*/DB_HOST=${{ secrets.DB_HOST }}/" .env
            sed -i "s/^DB_PORT=.*/DB_PORT=${{ secrets.DB_PORT }}/" .env
            sed -i "s/^DB_DATABASE=.*/DB_DATABASE=${{ secrets.DB_DATABASE }}/" .env
            sed -i "s/^DB_USERNAME=.*/DB_USERNAME=${{ secrets.DB_USERNAME }}/" .env
            sed -i "s/^DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/" .env

            sed -i "s/^BACKOFFICE_URL=.*/BACKOFFICE_URL=${{ secrets.BACKOFFICE_URL }}/" .env
            sed -i "s/^WEBSITE_URL=.*/WEBSITE_URL=${{ secrets.WEBSITE_URL }}/" .env

            sed -i "s/^MAIL_MAILER=.*/MAIL_MAILER=${{ secrets.MAIL_MAILER }}/" .env
            sed -i "s/^MAIL_HOST=.*/MAIL_HOST=${{ secrets.MAIL_HOST }}/" .env
            sed -i "s/^MAIL_PORT=.*/MAIL_PORT=${{ secrets.MAIL_PORT }}/" .env
            sed -i "s/^MAIL_USERNAME=.*/MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}/" .env
            sed -i "s/^MAIL_PASSWORD=.*/MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}/" .env
            sed -i "s/^MAIL_ENCRYPTION=.*/MAIL_ENCRYPTION=${{ secrets.MAIL_ENCRYPTION }}/" .env
            sed -i "s/^MAIL_FROM_ADDRESS=.*/MAIL_FROM_ADDRESS=${{ secrets.MAIL_FROM_ADDRESS }}/" .env

            sed -i "s/^RECAPTCHA_KEY=.*/RECAPTCHA_KEY=${{ secrets.RECAPTCHA_KEY }}/" .env

            composer2 install --no-dev --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan storage:link
          EOF
