name: Deploy Laravel App to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, intl, xml, curl, zip, opcache

      - name: Install dependencies
        run: |
          composer global require "composer/composer:2.*"  # Installe Composer 2
          composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd domains/luwa.fr/public_html/gp-api

            if [ ! -d ".git" ]; then
              git clone https://github.com/Granules-de-Bois-Picard/api.git .
            else
              git pull origin production
            fi

            if [ ! -f ".env" ]; then
              cp .env.example .env
            fi

            composer2 install --no-dev --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          EOF
